site_name: Zenvrm Docs
site_url: https://devzvrm.github.io/zenvrm-docs
dev_addr: 127.0.0.1:8100
theme: 
    name: material
    custom_dir: overrides
    logo: images/zenvrm-favicon-1.0.png
    favicon: images/zenvrm-favicon-1.0.png
    features:
      - navigation.tabs
      - navigation.sections
    palette:
        - scheme: default
          primary: white
          accent: teal
          toggle:
                icon: material/weather-sunny
                name: Switch to dark mode
        - scheme: slate
          primary: cyan
          toggle:
                icon: material/weather-night
                name: Switch to light mode
nav:
    - Home: index.md
    - Getting Started: 
      - Initial Setup: getting-started/setup.md
      - Module Basics: getting-started/modules.md
    - Application Deep Dive:
      - Dashboard: application/dashboard.md
      - Inbox: application/inbox.md
      - Reservations: application/reservations.md
      - Calendar: application/calendar.md
      - Properties: application/properties.md
      - Tasks: application/tasks.md
      - Staff: application/staff.md
      - Reports: application/reports.md
      - Settings: application/settings.md
      - Integrations: application/integrations.md
      - Automation Engine:
        - Reservations: automation/reservations.md
        - Smart Locks: automation/smartlocks.md
        - Tasks: automation/tasks.md
        - Dynamic Pricing: automation/pricing.md
        - Thermostat: automation/thermostat.md
        - Noise Monitoring: automation/noise.md
      
    #- Smart Home:
      #- home-controllers/index.md
      #- Ezlo: home-controllers/ezlo.md
      #- Vera: home-controllers/vera.md
      #- Ecobee: thermostats/ecobee.md
    #- Support: support.md
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<support@zenvrm.com>
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

